{
 "title": "Spring Boot 3",
 "description": "Dashboard for Spring Boot 3 (by micrometer-prometheus)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_info,application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info{application=\"$application\"},instance)"
    }
   },
   {
    "name": "kafka_topic",
    "label": "Kafka topic",
    "query": {
     "query": "label_values(kafka_consumer_current_offset{application=\"$application\", instance=\"$instance\"},topic)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Common Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Start Timings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_started_time_seconds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Startup time"
    },
    {
     "expr": "application_ready_time_seconds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Ready time"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Jvm Info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jvm_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "Heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "Non-Heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HTTP API RPS Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*|.*open-api.*|.*webjars.*\", outcome=\"SUCCESS\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*|.*open-api.*|.*webjars.*\", outcome!=\"SUCCESS\"}[5m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "HTTP API Response Time Per Second Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception=\"none\", uri!~\".*actuator.*|.*open-api.*|.*webjars.*\", outcome=\"SUCCESS\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception=\"none\", uri!~\".*actuator.*|.*open-api.*|.*webjars.*\", outcome=\"SUCCESS\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "avg(irate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception=\"none\", uri!~\".*actuator.*|.*open-api.*|.*webjars.*\", outcome!=\"SUCCESS\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception=\"none\", uri!~\".*actuator.*|.*open-api.*|.*webjars.*\", outcome!=\"SUCCESS\"}[5m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "DB Query Total Per Second ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(spring_data_repository_invocations_seconds_count{instance=\"$instance\", application=\"$application\", state=\"SUCCESS\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(irate(spring_data_repository_invocations_seconds_count{instance=\"$instance\", application=\"$application\", state!=\"SUCCESS\"}[5m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "DB Query Execution Time Per Second Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(spring_data_repository_invocations_seconds_sum{instance=\"$instance\", application=\"$application\", state=\"SUCCESS\"}[5m]) / irate(spring_data_repository_invocations_seconds_count{instance=\"$instance\", application=\"$application\", state=\"SUCCESS\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "avg(irate(spring_data_repository_invocations_seconds_sum{instance=\"$instance\", application=\"$application\", state!=\"SUCCESS\"}[5m]) / irate(spring_data_repository_invocations_seconds_count{instance=\"$instance\", application=\"$application\", state!=\"SUCCESS\"}[5m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Kafka Consumer Topics Lag Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_lag{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Logs Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(logback_events_total{instance=\"$instance\", application=\"$application\"}[5m]))",
     "legendFormat": "Logs",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "API RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*|.*open-api.*|.*webjars.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "API Response Time Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception=\"none\", uri!~\".*actuator.*|.*open-api.*|.*webjars.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception=\"none\", uri!~\".*actuator.*|.*open-api.*|.*webjars.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connection Pool Info",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "r2dbc_pool_allocated_connections{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Current size"
      },
      {
       "expr": "r2dbc_pool_max_allocated_connections{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Max size"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 5, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "r2dbc_pool_allocated_connections{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "r2dbc_pool_acquired_connections{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Acquired"
      },
      {
       "expr": "r2dbc_pool_idle_connections{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "r2dbc_pool_pending_connections{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Query Per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "irate(spring_data_repository_invocations_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{repository}}.{{method}} {{state}}"
      }
     ]
    },
    {
     "title": "Query Execution Time Per Second ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(spring_data_repository_invocations_seconds_sum{instance=\"$instance\", application=\"$application\"}[5m]) / irate(spring_data_repository_invocations_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{repository}}.{{method}} {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer Topic Lag - $kafka_topic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "kafka_consumer_lag{application=\"$application\", instance=\"$instance\", topic=\"${kafka_topic:string}\"}",
       "legendFormat": "{{groupId}} - {{topic}}[{{partition}}]"
      }
     ]
    },
    {
     "title": "Consumer Topic Current Offset - $kafka_topic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "repeat": "kafka_topic",
     "targets": [
      {
       "expr": "kafka_consumer_current_offset{application=\"$application\", instance=\"$instance\", topic=\"${kafka_topic:string}\"}",
       "legendFormat": "{{groupId}} - {{topic}}[{{partition}}]"
      }
     ]
    },
    {
     "title": "Topic End Offset - $kafka_topic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
     "repeat": "kafka_topic",
     "targets": [
      {
       "expr": "kafka_consumer_end_offset{application=\"$application\", instance=\"$instance\", topic=\"${kafka_topic:string}\"}",
       "legendFormat": "{{topic}}[{{partition}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
     "repeat": "memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"${memory_pool_heap:string}\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"${memory_pool_heap:string}\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"${memory_pool_heap:string}\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
     "repeat": "memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"${memory_pool_nonheap:string}\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"${memory_pool_nonheap:string}\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"${memory_pool_nonheap:string}\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Young gen allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Old gen promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Logs Total Per Second ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(logback_events_total{instance=\"$instance\", application=\"$application\"}[5m]))",
       "legendFormat": "Logs",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "Logs Trace Per Second ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\"}[5m])",
       "legendFormat": "Logs",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "Logs Debug Per Second ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\"}[5m])",
       "legendFormat": "Logs",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "Logs Info Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"info\"}[5m])",
       "legendFormat": "Logs",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "Logs Warn Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\"}[5m])",
       "legendFormat": "Logs",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "Logs Error Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"error\"}[5m])",
       "legendFormat": "Logs",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "disk_total_bytes{application=\"$application\", instance=\"$instance\"} - disk_free_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "disk_free_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "disk_total_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Process Open Files",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Open Files"
      },
      {
       "expr": "process_files_max_files{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Max Files"
      }
     ]
    }
   ]
  }
 ]
}