datasources:
  -  access: 'proxy'
     editable: true
     is_default: true
     name: 'Prometheus'
     uid: PBFA97CFB590B2093
     org_id: 1
     type: 'prometheus'
     url: 'http://prometheus:9090'
     version: 1