scrape_configs:
  - job_name: spring-boot
    scrape_interval: 5s
    metrics_path: /smftp-awesome-template/actuator/prometheus
    static_configs:
      - targets: ['http://host.docker.internal:8080']
        labels:
          application: 'smftp-awesome-template'